alias: "Morgon"
sequence:
  - service: switch.turn_on
    entity_id: switch.kitchen_coffeebrewer_switch

  - delay: 00:01:00

  - service: switch.turn_on
    entity_id: switch.livingroom_window_switch

  - service: light.turn_on
    entity_id: light.livingroom_cornerlight_level
    data:
      brightness: 100

  - delay: 00:00:30

  - service: switch.turn_on
    entity_id: switch.kitchen_window_switch

  - service: light.turn_on
    entity_id: light.livingroom_cornerlight_level
    data:
      brightness: 180

  - service: logbook.log
    data_template:
      name: Morgonl√§ge
      message: aktiverades
